backend:
  name: github
  repo: yuriburk/yuriburk-dev

media_folder: static/img/posts
public_folder: /img/posts

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: smallImage, label: Image, widget: image }
      - { name: description, label: Description }
      - { name: tags, widget: list }
      - { name: body, label: Body, widget: markdown }
